# ===============================
# = SPRING DATASOURCE (H2)
# ===============================
spring.datasource.url=jdbc:h2:mem:authdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# = JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# = THYMELEAF
# ===============================
spring.thymeleaf.cache=false

# ===============================
# = LOGGING
# ===============================
logging.level.org.springframework.security=INFO

# ===============================
# = SERVER
# ===============================
server.port=8080
